# Copyright 2024 Dynamic Solutions Sp. z o.o. sp.k.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for StreamX

# -- overwrites tenant for this release installation, defaults to `.Release.Name`
tenant:

# global settings inherited by all chart components
global:
  # -- global environment variables for all containers, can be overridden by component specific env
  env: []
  # -- imagePullSecrets used to authenticate to registry containing StreamX and custom images
  imagePullSecrets: []

monitoring:
  # -- enabling this flag will enable creating `monitoring.coreos.com` Custom Resources for all services
  enabled: false

# -- used to configure messaging system like Apache Pulsar, see the [Messaging](#messaging) section for reference
messaging: {}

# -- `Rest Ingestion Service` configuration, see the [REST Ingestion Service](#rest-ingestion-services) section for reference
rest_ingestion:
  # @ignored in generated docs
  enabled: true
  # @ignored in generated docs
  replicas: 1
  # @ignored in generated docs
  allInboxesTopicPatter: "inboxes/.*"
  # @ignored in generated docs
  ingress:
    enabled: false

# -- `Processing Services` map, see the [Processing Services](#processing-services) section for reference
processing: {}

# -- `Delivery Services` map, see the [Delivery Services](#delivery-services) section for reference
delivery: {}
