{{- if .Values.rest_ingestion.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamx.component.fullname" (dict "componentName" "rest-ingestion" "context" $) }}
  labels:
    {{- include "streamx.component.labels" (dict "componentName" "rest-ingestion" "context" $) | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    {{- include "streamx.component.selectorLabels" (dict "componentName" "rest-ingestion" "context" $) | nindent 4 }}
{{- end }}