{{- if .Values.rest_ingestion.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streamx.component.fullname" (dict "componentName" "rest-ingestion" "context" $) }}
  labels:
    {{- include "streamx.component.labels" (dict "componentName" "rest-ingestion" "context" $) | nindent 4 }}
spec:
  replicas: {{ .Values.rest_ingestion.replicas }}
  selector:
    matchLabels:
      {{- include "streamx.component.selectorLabels" (dict "componentName" "rest-ingestion" "context" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "streamx.component.labels" (dict "componentName" "rest-ingestion" "context" $) | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.rest_ingestion.nodeSelector }}
      nodeSelector: {{- .Values.rest_ingestion.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: rest-ingestion
          image: {{ .Values.rest_ingestion.image }}
          imagePullPolicy: {{ .Values.rest_ingestion.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080          
          env:
            {{- include "streamx.pulsarEnvs" $ | nindent 12 }}
            - name: MP_MESSAGING_OUTGOING_ALL-INBOXES_TOPICSPATTERN
              value: {{ include "streamx.pulsarTopic" (dict "namespaceAndTopic" .Values.rest_ingestion.allInboxesTopicPatter "context" $) }}
            - name: MP_MESSAGING_OUTGOING_ALL-INBOXES_PRODUCERNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if .Values.rest_ingestion.env }}
{{ toYaml .Values.rest_ingestion.env | indent 12 }}
            {{- end }}
        {{- if .Values.rest_ingestion.resources }}
          resources:
{{ toYaml .Values.rest_ingestion.resources | indent 12 }}
        {{- end }}
        {{- if .Values.rest_ingestion.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.rest_ingestion.livenessProbe | indent 12 }}
        {{- end }}
        {{- if .Values.rest_ingestion.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.rest_ingestion.readinessProbe | indent 12 }}
        {{- end }}
        {{- if .Values.rest_ingestion.startupProbe }}
          startupProbe:
{{ toYaml .Values.rest_ingestion.startupProbe | indent 12 }}
        {{- end }}

{{- end }}