# Copyright 2024 Dynamic Solutions Sp. z o.o. sp.k.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## StreamX REST Ingestion Service
rest_ingestion:
  # -- enables REST Ingestion Service
  enabled: true
  # -- number of replicas
  replicas: 1
  # -- custom image and tag for tenant initialisation, the default image tag corresponds the current chart's AppVersion
  image: ghcr.io/streamx-dev/streamx/rest-ingestion-service:<appVersion>
  # -- all-inboxes topic pattern in format: `namespace/topic-regex`
  allInboxesTopicPatter: "inboxes/.*"
  # -- additional environment variables
  env: []
  # -- pod monitoring configuration
  monitoring: {}
  # -- probes settings, see tests for reference
  probes: {}
  # -- image pull policy
  imagePullPolicy:
  ingress:
    # -- enables ingress
    enabled: false
    # -- additional ingress annotations
    annotations: {}
    # -- (string) host for the ingress and TLS certificate
    host: 
    tls:
      # -- (string) secret name for the TLS certificate, set the value and `host` to enable TLS
      secretName:
    # -- ingress class name
    ingressClassName: nginx
  # -- resources for the container
  resources: {}
  # -- node labels for pod assignment
  nodeSelector: {}
