# Copyright 2024 Dynamic Solutions Sp. z o.o. sp.k.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

messaging:
  pulsar:
    # -- mandatory: Apache Pulsar Broker Service URL, e.g. `"pulsar://pulsar-service:6650"`
    serviceUrl:
    # -- mandatory: Apache Pulsar REST API URL, e.g. `"http://pulsar-web-service:8080"`
    webServiceUrl:
    initTenant:
      # -- enable Apache Pulsar tenant and namespaces initialisation for StreamX, this will create a Job that waits for Apache Pulsar to be ready
      enabled: false
      # -- custom image and tag for tenant initialisation, the default image tag corresponds the current chart's AppVersion
      image: ghcr.io/streamx-dev/streamx/pulsar-init:<appVersion>
      partitions:
        # -- optional: number of partitions for inboxes topics, defaults to `3`
        inboxes: 3
        # -- optional: number of partitions for relays topics, defaults to `3`
        relays: 3
        # -- optional: number of partitions for outboxes topics, defaults to `3`
        outboxes: 3
      # -- optional: additional environment variables for tenant initialisation
      env: []