# Copyright 2024 Dynamic Solutions Sp. z o.o. sp.k.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- range $name, $processing := .Values.processing }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streamx.component.fullname" (dict "componentName" (printf "%s-%s" "processing" $name ) "context" $) }}
  labels:
    {{- include "streamx.component.labels" (dict "componentName" (printf "%s-%s" "processing" $name ) "context" $) | nindent 4 }}
spec:
  replicas: {{ if hasKey $processing "replicas" }}{{ $processing.replicas }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      {{- include "streamx.component.selectorLabels" (dict "componentName" (printf "%s-%s" "processing" $name ) "context" $) | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "streamx.component.labels" (dict "componentName" (printf "%s-%s" "processing" $name ) "context" $) | nindent 8 }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets: {{- $.Values.global.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      {{- if $processing.terminationGracePeriod }}
      terminationGracePeriodSeconds:  {{ $processing.terminationGracePeriod }}
      {{- end }}
      {{- if $processing.nodeSelector }}
      nodeSelector: {{- $processing.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: {{ $processing.image }}
          imagePullPolicy: {{ $processing.imagePullPolicy }}
          ports:
            - name: metrics
              containerPort: 8080
          {{- if $processing.command }}
          command:
            {{- range $cmd := $processing.command }}
            - {{ $cmd | quote }}
            {{- end }}
          {{- end }}
          {{- if $processing.args }}
          args:
            {{- range $arg := $processing.args }}
            - {{ $arg | quote }}
            {{- end }}
          {{- end }}
          env:
            {{- include "streamx.mergeEnvs" (dict "baseEnvs" $.Values.global.env "overwriteEnvs" $processing.env) | nindent 12 }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- include "streamx.pulsarEnvs" $ | nindent 12 }}
            {{- include "streamx.component.quasarEnvs" (dict "componentName" (printf "%s-%s" "processing" $name ) "context" $) | nindent 12 }}
            - name: PLUGIN_STORE_TENANT
              value: {{ include "streamx.tenant" $ }}
            {{- range $key, $channel := $processing.incoming }}
            - name: MP_MESSAGING_INCOMING_{{ $key | upper }}_TOPIC
              value: {{ include "streamx.channelTopic" (dict "channel" $channel "context" $) }}
            {{- end }}
            {{- range $key, $channel := $processing.outgoing }}
            - name: MP_MESSAGING_OUTGOING_{{ $key | upper }}_TOPIC
              value: {{ include "streamx.channelTopic" (dict "channel" $channel "context" $) }}
            - name: MP_MESSAGING_OUTGOING_{{ $key | upper }}_PRODUCERNAME
              value: "$(POD_NAME)-{{ $key }}"
            {{- end }}
          resources:
          {{- if $processing.resources }}          
{{ toYaml $processing.resources | indent 12 }}
          {{- else }}
            requests:
              cpu: 400m
              memory: 256Mi
          {{- end }}
          {{- include "streamx.quarkusProbesConfig" (dict "probes" $processing.probes "context" $) | indent 10 }}
---
{{- end }}