{{- range $name, $processing := .Values.processing }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "streamx.component.fullname" (dict "componentName" (printf "%s-%s" "processing" $name ) "context" $) }}
  labels:
    {{- include "streamx.component.labels" (dict "componentName" (printf "%s-%s" "processing" $name ) "context" $) | nindent 4 }}
    release: {{ $.Release.Name }}
spec:
  jobLabel: app.kubernetes.io/component
  podMetricsEndpoints:
    - port: metrics
      path: {{ ($processing.podMonitor).path | default "/q/metrics" }}
      scheme: http
      interval: {{ ($processing.podMonitor).interval | default "10s" }}
      scrapeTimeout: {{ ($processing.podMonitor).scrapeTimeout | default "10s" }}
      relabelings:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - sourceLabels: [__meta_kubernetes_namespace]
          action: replace
          targetLabel: kubernetes_namespace
        - sourceLabels: [__meta_kubernetes_pod_label_component]
          action: replace
          targetLabel: job
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: kubernetes_pod_name
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: instance
        - sourceLabels: [__meta_kubernetes_pod_container_name]
          action: replace
          targetLabel: application
  selector:
    matchLabels:
      {{- include "streamx.component.selectorLabels" (dict "componentName" (printf "%s-%s" "processing" $name ) "context" $) | nindent 6 }}
---
{{- end }}