{{- range $name, $processing := .Values.processing }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streamx.component.fullname" (dict "componentName" $name "context" $) }}
  labels:
    {{- include "streamx.component.labels" (dict "componentName" $name "context" $) | nindent 4 }}
spec:
  replicas: {{ if hasKey $processing "replicas" }}{{ $processing.replicas }}{{ else }}1{{ end }}
  selector:
    matchLabels:
      {{- include "streamx.component.selectorLabels" (dict "componentName" $name "context" $) | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "streamx.component.labels" (dict "componentName" $name "context" $) | nindent 8 }}
    spec:
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets: {{- $.Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      {{- if $processing.terminationGracePeriod }}
      terminationGracePeriodSeconds:  {{ $processing.terminationGracePeriod }}
      {{- end }}
      {{- if $processing.nodeSelector }}
      nodeSelector: {{- $processing.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: {{ $processing.image }}
          imagePullPolicy: {{ $processing.imagePullPolicy }}
          ports:
            - name: metrics
              containerPort: 8080
          {{- if $processing.command }}
          command:
            {{- range $cmd := $processing.command }}
            - {{ $cmd | quote }}
            {{- end }}
          {{- end }}
          {{- if $processing.args }}
          args:
            {{- range $arg := $processing.args }}
            - {{ $arg | quote }}
            {{- end }}
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PULSAR_ADMIN_SERVICEURL
              value: {{ $.Values.pulsar.webServiceUrl }}
            - name: PULSAR_CLIENT_SERVICEURL
              value: {{ $.Values.pulsar.serviceUrl }}
            - name: QUASAR_MESSAGING_DATASTORE_PULSAR_SERVICEURL
              value: {{ $.Values.pulsar.serviceUrl }}
            - name: PLUGIN_STORE_TENANT
              value: {{ include "streamx.tenant" $ }}
            {{- range $key, $channel := $processing.incoming }}
            - name: MP_MESSAGING_INCOMING_{{ $key | upper }}_TOPIC
              value: {{ include "streamx.channelTopic" (dict "channel" $channel "context" $) }}
            {{- end }}
            {{- range $key, $channel := $processing.outgoing }}
            - name: MP_MESSAGING_OUTGOING_{{ $key | upper }}_TOPIC
              value: {{ include "streamx.channelTopic" (dict "channel" $channel "context" $) }}
            - name: MP_MESSAGING_OUTGOING_{{ $key | upper }}_PRODUCERNAME
              value: "$(POD_NAME)-{{ $key }}"
            {{- end }}
            {{- if $processing.env }}
{{ toYaml $processing.env | indent 12 }}
            {{- end }}
          resources:
          {{- if $processing.resources }}          
{{ toYaml $processing.resources | indent 12 }}
          {{- else }}
            requests:
              cpu: 400m
              memory: 256Mi
          {{- end }}
---
{{- end }}