# Copyright 2024 Dynamic Solutions Sp. z o.o. sp.k.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Test: Verify StreamX Helm chart'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Run chart helm-unittest
        run: |
          cd chart
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
          helm unittest -f 'tests/unit/*.yaml' .

      - name: Verify reference example
        run: |
          helm template --output-dir generated streamx ./chart \
            --set pulsar.serviceUrl="pulsar://service.pulsar:6650" \
            --set pulsar.webServiceUrl="http://web-service.pulsar:8080" \
            --set rest_ingestion.ingress.host="streamx-api.127.0.0.1.nip.io" \
            -f examples/reference/ingestion.yaml -f examples/reference/processing.yaml -f examples/reference/delivery.yaml