name: 'Test: Verify StreamX Helm chart'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Run chart helm-unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
          helm unittest -f 'tests/unit/*.yaml' .

      - name: Verify reference example
        run: |
          helm template --output-dir generated test . \
            --set pulsar.serviceUrl="pulsar://service.pulsar:6650" \
            --set pulsar.webServiceUrl="http://web-service.pulsar:8080" \
            --set rest_ingestion.ingress.host="streamx-api.127.0.0.1.nip.io" \
            -f examples/dummy/processing.yaml -f examples/dummy/delivery.yaml